//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Лаба_9
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public Nullable<int> Id_client { get; set; }
        public Nullable<int> Id_service { get; set; }
        public Nullable<System.DateTime> Date_completion { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual Сlient Сlient { get; set; }
    }
}
